version: "3.7"
services:
  locust:
    image: locustio/locust
    container_name: my-locust
    environment:      
      TARGET_URL: http://10.22.0.249
      LUCUST_OPTS: "-C 10 -r 10"      
      LOCUSTFILE_PATH: /mnt/locust/locustfile.py
    ports: 
      - 8089:8089
    volumes:
      - ./locust:/mnt/locust